travis:
  secure:
    BINSTAR_TOKEN: eZh2tvLunneYhVxKNzpjaUDOhYZh7GJeOEE/kER+cBZUfXqhLsy/G16reg1bjEpFlRp38UmDsw5ZrSpM7snSCCnA43sU+RiITbR7SR5ErWgvX0mEqyVgiawJPAlNVhrocZWlBCEyOHcu70UU4OHOTMuZO7R7ZOKzPNAFIR0c/dzq7fNLKdPFOT+dzSbB6DMjcq1aYZMe4nvXEW65wOomJ1L0lw3MM9i2ifCYW/aZ45TcFsS2dFmdbvaK5wwSy7ZLxcIi6+TeJGrA9Td+Qlhf9kS9B8ePhu1JZHxod9EBG7br18iYwM89JdapGdWhCbzeKjcigZ99HS7YRKfJU5mo92PQ7mm4vFXHZ9zusohkdbgQ1BvNJXf9KQzK664a/U7b61uZjWvFbEj8gX5/kAsMAjYjvlUkwIWwachy+NDBi9HycncENc3vs31Kbr4nHPbwNA0+xn2FvDliTb99M54pHDd9g/nqI2eNyfKfIJUy/KLbHrvW/a/vE2/splgqNHkVQKWcViU9LpeG73UDsFoOIQ/f9PMpHw+hLdbfeXZBLM/VzwPMj3XtrpDVRrFRTAOlIQgKJ6F/MVVUAmJvMcPRIE1gyXXEdCvnED7DRs5eBeV3wBOSrN78yz6IHgXD5wjRYZOEkXbiTimWMOZkZ4I1Gu0IhAT/1y4BUK1Fo/h1rG4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
